name: 'Wait for Deployment Validation'
description: 'Polls Maven Central deployment status until validated or failed'

inputs:
  deployment-id:
    description: 'Maven Central deployment ID'
    required: true
  expected-state:
    description: 'Expected deployment state to wait for (VALIDATED, PUBLISHING, PUBLISHED)'
    required: true
  max-attempts:
    description: 'Maximum number of polling attempts'
    required: false
    default: '30'
  poll-interval:
    description: 'Seconds between polling attempts'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Wait for deployment state
      uses: ./.github/actions/poll-until-condition
      with:
        check-script: '../wait-for-deployment-validation/check-deployment-state.ps1'
        script-args: '${{ inputs.deployment-id }} ${{ inputs.expected-state }}'
        max-attempts: '${{ inputs.max-attempts }}'
        poll-interval: '${{ inputs.poll-interval }}'
        condition-name: 'deployment state ${{ inputs.expected-state }}'
